name: sunat_vouchers
description: Aplicaci贸n m贸vil para el registro y verificaci贸n de comprobantes con SUNAT y autenticaci贸n de Google
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.8.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_ui_auth: ^1.5.0
  firebase_ui_localizations: ^1.5.0
  firebase_ui_oauth: ^1.4.4
  firebase_ui_oauth_google: ^1.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^12.1.1
  google_sign_in: ^6.1.4
  intl: ^0.18.0
  json_annotation: ^4.8.1
  uuid: ^4.0.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Ubuntu-Bold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
    - family: Ubuntu-Light
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
    - family: Ubuntu-Medium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  image_path_android: "assets/images/app_icon.png"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/app_icon.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
