name: sunat_vouchers
description: Aplicaci贸n m贸vil para el registro y verificaci贸n de comprobantes con SUNAT y autenticaci贸n de Google
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.6.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_localizations: ^1.13.0
  firebase_ui_oauth: ^1.6.0
  firebase_ui_oauth_google: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Ubuntu-Bold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
    - family: Ubuntu-Light
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
    - family: Ubuntu-Medium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  image_path_android: "assets/images/app_icon.png"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/app_icon.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
